#!/usr/bin/env bash

(cd ../../local && make -j8 DIM=2 USE_EB=FALSE AMREX_PARTICLES=TRUE)

EXE=../../local/MFP.2d.gnu.MPI.PARTICLES.ex

INPUTS=TRMI.inputs

rm -r *chk* *plt*
rm -r mov

mpirun -n 8 ${EXE} ${INPUTS} 2>&1 | tee run_log.txt

python3 plot.py
# python3 movie.py
